DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS acc_transfer;

CREATE TABLE account (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT UNIQUE NOT NULL,
  date_joined DATE NOT NULL,
  cpf VARCHAR(11) UNIQUE NOT NULL,
  balance INTEGER NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE acc_transfer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  account_origin_id TEXT NOT NULL,
  account_destiantion_id TEXT NOT NULL,
  amount INTEGER NOT NULL,
  created_at DATE NOT NULL
);