GET http://localhost:1323/transfers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcGYiOiIxMjM0NTY3ODkwMiIsImV4cCI6MTY2NTIwMjcyNn0.UvMPdgGiPKrmYwpvh_ibCXhuSmKpb8oK9F9Q7DmpO94