GET http://localhost:1323/transfers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcGYiOiIxMjM0NTY3ODkwMiIsImV4cCI6MTY2NTA4NTA0NH0.U4nLGfe8xllznctvNuABSOmDSw-AiYxCl2wuCZLotRU

GET http://localhost:1323/transfers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcGYiOiIxMjM0NTY3ODkwMyIsImV4cCI6MTY2NTA4NTg3OH0.33cYYx6PprjtmzrTiGIrdWSwz49y-gtW09rq-3SN10Q
