POST http://localhost:1323/accounts HTTP/1.1
content-type: application/json

{
    "name": "Paulo",
    "cpf": "12345678902",
    "secret": "123456"
}


POST http://localhost:1323/accounts HTTP/1.1
content-type: application/json

{
    "name": "Paula",
    "cpf": "12345678903",
    "secret": "123456"
}