POST http://localhost:1323/transfers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcGYiOiIxMjM0NTY3ODkwNCIsImV4cCI6MTY2NTExNTY3N30.fVzisO5PBJyJyPxysjREKSq3WxPK-VhbijyBbwsmRAk

{
    "destination_cpf": "12345678905",
    "amount": 200
}

POST http://localhost:1323/transfers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcGYiOiIxMjM0NTY3ODkwMyIsImV4cCI6MTY2NTA4NTg3OH0.33cYYx6PprjtmzrTiGIrdWSwz49y-gtW09rq-3SN10Q

{
    "destination_cpf": "12345678902",
    "amount": 700
}