POST http://localhost:1323/login HTTP/1.1
content-type: application/json

{
    "cpf": "12345678904",
    "secret": "123456"
}

POST http://localhost:1323/login HTTP/1.1
content-type: application/json

{
    "cpf": "12345678903",
    "secret": "123456"
}