GET http://localhost:8080/transfers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcGYiOiIxMjM0NTY3ODkwNCIsImV4cCI6MTY2NjI4NzEyMn0.oETT0uzkSlzhG81Nu5h-MAcQx6Fxya-2bAYJ5iObS9w

GET http://localhost:8080/transfers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcGYiOiIxMjM0NTY3ODkwMyIsImV4cCI6MTY2NjI5MDg5M30.gTXTKS42ObRWzbLkLjVcjrPkuDuXXSNuaUpg2hiEvDU
