POST http://localhost:1323/accounts HTTP/1.1
content-type: application/json

{
    "name": "Paulo",
    "cpf": "12345678905",
    "secret": "123456"
}


POST http://localhost:1323/accounts HTTP/1.1
content-type: application/json

{
    "name": "Carina",
    "cpf": "12345678903",
    "secret": "123456"
}

POST http://localhost:1323/accounts HTTP/1.1
content-type: application/json

{
    "name": "Juliana",
    "cpf": "12345678904",
    "secret": "123456"
}